apiVersion: v1
kind: Pod
metadata:
  name: chris
spec:
  containers:
    - name: chris
      image: ghcr.io/fnndsc/cube:4.0.0.pre6
      ports:
        - containerPort: 8000
      env:
        - name: DJANGO_DB_MIGRATE
          value: "on"
        - name: DJANGO_COLLECTSTATIC
          value: "on"
      envFrom:
        - configMapRef:
            name: secrets
      volumeMounts:
        - name: chris-db
          mountPath: /var/lib/postgresql/data:Z
      restartPolicy: OnFailure
    - name: worker
      image: ghcr.io/fnndsc/cube:4.0.0.pre6
      ports:
        - containerPort: 8000
      env:
        - name: DJANGO_DB_MIGRATE
          value: "on"
        - name: DJANGO_COLLECTSTATIC
          value: "on"
      envFrom:
        - configMapRef:
            name: secrets
      volumeMounts:
        - name: chris-db
          mountPath: /var/lib/postgresql/data:Z
      restartPolicy: OnFailure
    - name: chris-ui
      image: ghcr.io/fnndsc/chris_ui:20230223.203-f0074403
      command: ["sirv", "--host", "--single"]
      env:
        - name: REACT_APP_CHRIS_UI_URL
          value: "http://localhost:8000/api/v1/"
        - name: REACT_APP_PFDCM_URL
          value: "http://localhost:4005/"
      ports:
        - containerPort: 3000
          hostPort: 8020
    - name: chris-store-ui
      image: ghcr.io/fnndsc/chris_store_ui:0.2.1
      command: ["sirv", "--host", "--single"]
      env:
        - name: REACT_APP_STORE_URL
          value: "http://localhost:8010/api/v1/"
      ports:
        - containerPort: 3000
          hostPort: 8021
    #### INSERT NEW YAML BELOW THIS LINE ####
  volumes:
    - name: chris-db
      hostPath:
        path: /var/lib/containers/storage/volumes/chris-db
      #### INSERT NEW YAML BELOW THIS LINE FOR STORAGE ####