---
apiVersion: apps/v1

kind: Deployment
metadata:
  name: minichris-rabbitmq
  labels:
    app: minichris-rabbitmq
    app.kubernetes.io/component: queue
    app.kubernetes.io/part-of: miniChRIS
  annotations:
    kubernetes.io/description: "ChRIS backend asynchronous task queue"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minichris-rabbitmq
  template:
    metadata:
      name: minichris-rabbitmq
      labels:
        app: minichris-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: docker.io/library/rabbitmq:3
