---

apiVersion: v1
kind: ConfigMap
metadata:
  name: minichris-cube-config
  labels:
    app.kubernetes.io/part-of: miniChRIS
  annotations:
    kubernetes.io/description: "Configuration of ChRIS backend production mode, security options, and secrets"
data:
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  CUBE_CELERY_POLL_INTERVAL: "5.0"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_SECRET_KEY: "secret"
  DJANGO_CORS_ALLOW_ALL_ORIGINS: "true"
  DJANGO_CORS_ALLOWED_ORIGINS: ""
  DJANGO_SECURE_PROXY_SSL_HEADER: ""
  DJANGO_USE_X_FORWARDED_HOST: "false"
  STATIC_ROOT: "/home/localuser/mod_wsgi-0.0.0.0:8000/htdocs/static/"
  AUTH_LDAP: "false"
  CHRIS_STORE_URL: "https://chrisstore.co/api/v1/"
  DATABASE_HOST: "minichris-postgres-pod"
  DATABASE_PORT: "5432"
  CELERY_BROKER_URL: "amqp://minichris-rabbitmq-pod:5672"
  SWIFT_AUTH_URL: "http://minichris-swift-pod:8080/auth/v1.0"
  SWIFT_CONTAINER_NAME: "users"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: minichris-db-config
  labels:
    app.kubernetes.io/part-of: miniChRIS
  annotations:
    kubernetes.io/description: "Configuration of a PostgresSQL databse used by the ChRIS backend"
data:
  POSTGRES_DB: "chris"
  POSTGRES_USER: "chris"
  POSTGRES_PASSWORD: "chris1234"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: minichris-docker-swift-onlyone-config
  labels:
    app.kubernetes.io/part-of: miniChRIS
  annotations:
    kubernetes.io/description: "Configuration of the swift container"
data:
  SWIFT_USERNAME: "chris:chris1234"
  SWIFT_KEY: "testing"
