apiVersion: apps/v1
kind: Pod
metadata:
  name: cube
  spec:
    containers:
      - name: cube
        envFrom:
          - configMapRef:
              name: secrets
        image: ghcr.io/fnndsc/cube:4.0.0.pre6
        ports:
          - containerPort: 8000
        resources: {}
  restartPolicy: Always
status: {}
