apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/extract-local: "true"
    io.kompose.service: queue
  name: queue
spec:
  containers:
    - image: docker.io/library/rabbitmq:3
      name: queue
      resources: {}
  restartPolicy: OnFailure
status: {}
