---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: chrisstoredb-pod
  name: chrisstoredb-pod
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_DB
      value: chris_store
    - name: POSTGRES_PASSWORD
      value: chirs1234
    - name: POSTGRES_USER
      value: crhis
    - name: DATABASE_PORT
      value: 5432=5433
    image: docker.io/library/postgres:13
    name: chrisstoredb
    ports:
    - containerPort: 5432
      hostPort: 5432
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    tty: true
    volumeMounts:
    - mountPath: /var/lib/postgresql
      name: chris_store_db_data-pvc
  volumes:
  - name: chris_store_db_data-pvc
    persistentVolumeClaim:
      claimName: chris_store_db_data
