apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store
  name: chris-store
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chris-store
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/extract-local: "true"
        io.kompose.service: chris-store
    spec:
      containers:
        - env:
            - name: DATABASE_HOST
              value: chris_store_db
            - name: DATABASE_PORT
              value: "5432"
            - name: DJANGO_ALLOWED_HOSTS
              value: '*'
            - name: DJANGO_CORS_ALLOWED_ORIGINS
              value: https://babymri.org
            - name: DJANGO_CORS_ALLOW_ALL_ORIGINS
              value: "true"
            - name: DJANGO_DB_MIGRATE
              value: "on"
            - name: DJANGO_SECRET_KEY
              value: secret
            - name: DJANGO_SECURE_PROXY_SSL_HEADER
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.production
            - name: DJANGO_USE_X_FORWARDED_HOST
              value: "false"
            - name: POSTGRES_DB
              value: chris_store
            - name: POSTGRES_PASSWORD
              value: chirs1234
            - name: POSTGRES_USER
              value: chris
          image: ghcr.io/fnndsc/chris_store:2.2.0
          name: chris-store
          ports:
            - containerPort: 8010
          resources: {}
      restartPolicy: Always
status: {}
