apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: orthanc
  name: orthanc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orthanc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/extract-pacs: "true"
        io.kompose.service: orthanc
    spec:
      containers:
        - image: docker.io/jodogne/orthanc-plugins:1.11.0
          name: orthanc
          ports:
            - containerPort: 4242
            - containerPort: 8042
          resources: {}
          volumeMounts:
            - mountPath: /etc/orthanc/orthanc.json
              name: orthanc-claim0
              readOnly: true
            - mountPath: /var/lib/orthanc/db
              name: orthanc
      restartPolicy: Always
      volumes:
        - name: orthanc-claim0
          persistentVolumeClaim:
            claimName: orthanc-claim0
            readOnly: true
        - name: orthanc
          persistentVolumeClaim:
            claimName: orthanc
status: {}
