name: Podman Deployment CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: get version of podman
      run: |
        podman --version

    - name: minichris_up
      run: |
        ls -lath ./minichris.sh || exit $?
        bash -x ./minichris.sh up

    - name: Sleep for 60s
      uses: juliangruber/sleep-action@v1
      with:
        time: 60s

    - name: Pod Health Check Testing Networking  
      run: | 
        pwd
        echo "Testing Networking"
        echo "If there is 1 container in pod that means the container has not started but the infra container has started"
        echo "If there are 2 containers in pod that means the networking is working for that pod"
        sudo podman ps 
        sudo podman pod ps 
        /home/runner/work/miniChRIS-podman-pod/miniChRIS-podman-pod/check_pods.sh

    - name: Testing Environment
      run: |
        sudo podman ps 
        sudo podman ps --all --format "{{.Names}} {{.Ports}} {{.Mounts}} {{.Status}}"
        sudo podman stats --no-stream
        sudo podman pod stats --no-stream

    - name: Advanced tests
      run: | 
          podman pod logs -c chris_db-chris_db chris_db
          podman pod logs -c chris_store_db-chris_store_db chris_store_db



    - name: minichris_down
      run: |
        ./minichris.sh down
