name: Podman Deployment CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test podman-network-chris
      run: |
        make create-podman-network-chris
        make run-podman-network-chris
        sudo podman network ls || exit $?

    - name: Test chris-db-pod
      run: |
        make create-volume-chris-db
        make run-chris-db-pod
        sudo podman pod ps || exit $?

    - name: Test chris-store-db-pod
      run: |
        make create-volume-chris-store-db
        make run-chris-store-db-pod
        sudo podman pod ps || exit $?

    - name: Test swift-pod
      run: |
        make create-volume-swift
        make run-swift-pod
        sudo podman pod ps || exit $?

    - name: Test cube-pod
      run: |
        make run-cube-pod
        sudo podman pod ps || exit $?

    - name: Test chris-ui-pod
      run: |
        make run-chris-ui-pod
        sudo podman pod ps || exit $?

    - name: Test chris-store-pod
      run: |
        make run-chris-store-pod
        sudo podman pod ps || exit $?

    - name: Test chris-store-ui-pod
      run: |
        make run-chris-store-ui-pod
        sudo podman pod ps || exit $?

    - name: Test worker-pod
      run: |
        make run-worker-pod
        sudo podman pod ps || exit $?

    - name: Test rabbit-mq-pod
      run: |
        make run-rabbit-mq-pod
        sudo podman pod ps || exit $?

    - name: Test orthanc-pod
      run: |
        make create-volume-orthanc
        make run-orthanc-plugins-pod
        sudo podman pod ps || exit $?

    - name: Test scheduler-pod
      run: |
        make run-scheduler-pod
        sudo podman pod ps || exit $?

    - name: Test pfdcm-pod
      run: |
        make run-pfdcm-pod
        sudo podman pod ps || exit $?

    - name: Test pfdcm-listener-pod
      run: |
        make run-pfdcm-listener-pod
        sudo podman pod ps || exit $?

    - name: Test pfcon-pod
      run: |
        make create-volume-pfcon
        make run-pfcon-pod
        sudo podman pod ps || exit $?

    - name: Test pman-pod
      run: |
        make create-volume-pman
        make run-pman-pod
        sudo podman pod ps || exit $?

    - name: Sleep for 60s
      uses: juliangruber/sleep-action@v1
      with:
        time: 60s
        
    - name: Testing Environment
      run: |
        sudo podman ps 
        sudo podman ps --all --format "{{.Names}} {{.Ports}} {{.Mounts}} {{.Status}}"
        sudo podman stats --no-stream
        sudo podman pod stats --no-stream

    - name: Stop All running Pods
      run: |
        sudo podman pod ps || exit $?
        sudo podman pod stop --all
        sudo podman pod rm --all
