name: Podman Deploymet CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test run-chris-db-pod
      run: |
        make create-volume-chris-db
        make run-chris-db-pod
        sudo podman pod ps || exit $?
        sudo podman pod stop chris_db_pod || exit $?

    - name: Test worker-pod
      run: |
        make run-worker-pod
        sudo podman pod ps || exit $?
        sudo podman pod stop worker_pod || exit $?

