name: Podman Deployment CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test chris-db-pod
      run: |
        make create-volume-chris-db
        make run-chris-db-pod
        sudo podman pod ps || exit $?

    - name: Test worker-pod
      run: |
        make run-worker-pod
        sudo podman pod ps || exit $?

    - name: Test chris-pod
      run: |
        make run-chris-pod
        sudo podman pod ps || exit $?

    - name: Test rabbit-mq-pod
      run: |
        make run-rabbit-mq-pod
        sudo podman pod ps || exit $?

    - name: Test scheduler-pod
      run: |
        make run-scheduler-pod
        sudo podman pod ps || exit $?

    - name: Test pfcon-pod
      run: |
        make run-pfcon-mq-pod
        sudo podman pod ps || exit $?

    - name: Sleep for 60s
      uses: juliangruber/sleep-action@v1
      with:
        time: 60s
        
    - name: Testing Enviornment
      run: |
        sudo podman ps 
        sudo podman ps --all --format "{{.Names}} {{.Ports}} {{.Mounts}} {{.Status}}"
        sudo podman stats --no-stream
        sudo podman pod stats --no-stream

    - name: Stop All Pods
      run: |
        sudo podman pod ps || exit $?
        sudo podman pod stop --all
        sudo podman pod rm --all
